  backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install backend deps
        run: npm install

      # 👇 요거 삭제함
      # - name: Run backend tests (optional)
      #   run: npm test --if-present

      - name: Build backend Docker image
        run: docker build -t lhb_web_server .
